version: "3.4"

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: docker-files/postgresql/
    image: tvclick/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backups:/backups
    env_file: development.env

  backend:
    build:
      context: .
      dockerfile: docker-files/backend/Dockerfile
    image: tvclick/backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
      - "3333:3333"
    env_file: development.env

  frontend:
    container_name: frontend
    image: tvclick/frontend
    restart: always
    build:
      context: .
      dockerfile: docker-files/frontend/Dockerfile
      args:
        - REACT_APP_API_URL=https://localhost:5000/
    ports:
      - '3000:80'
    restart: always
