version: "3.4"

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    container_name: channel_monitor_db
    build: docker-files/postgresql/
    image: tvclick/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./backups:/backups
    env_file: development.env
    restart: always

  backend:
    container_name: channel_monitor_backend
    image: tvclick/backend
    build:
      context: .
      dockerfile: docker-files/backend/Dockerfile
    depends_on:
      - postgres
    ports:
      - "5000:5000"
      - "3333:3333"
    env_file: development.env
    restart: always

  frontend:
    container_name: channel_monitor_frontend
    image: tvclick/frontend
    build:
      context: .
      dockerfile: docker-files/frontend/Dockerfile
      args:
        - REACT_APP_API_URL=http://192.168.15.6:5000/api
    ports:
      - '3000:80'
    restart: always
