export const SET_CHANNEL_ERROR = "SET_CHANNEL_ERROR";
export const SET_PROVIDER_ERROR = "SET_PROVIDER_ERROR";
export const SET_CHANNEL_LOADING = "SET_CHANNEL_LOADING";
export const SET_PROVIDER_LOADING = "SET_PROVIDER_LOADING";
export const SET_SERVER_ERROR = "SET_SERVER_ERROR";
export const SET_SERVER_LOADING = "SET_SERVER_LOADING";

export const FETCH_CHANNELS_SUCCESS = "FETCH_CHANNELS_SUCCESS";
export const FETCH_CHANNEL_SUCCESS = "FETCH_CHANNEL_SUCCESS";
export const POST_CHANNEL_SUCCESS = "POST_CHANNEL_SUCCESS";
export const PUT_CHANNEL_SUCCESS = "PUT_CHANNEL_SUCCESS";
export const DELETE_CHANNEL_SUCCESS = "DELETE_CHANNEL_SUCCESS";

export const FETCH_PROVIDERS_SUCCESS = "FETCH_PROVIDERS_SUCCESS";
export const FETCH_PROVIDER_SUCCESS = "FETCH_PROVIDER_SUCCESS";
export const POST_PROVIDER_SUCCESS = "POST_PROVIDER_SUCCESS";
export const PUT_PROVIDER_SUCCESS = "PUT_PROVIDER_SUCCESS";
export const DELETE_PROVIDER_SUCCESS = "DELETE_PROVIDER_SUCCESS";

export const FETCH_SERVERS_SUCCESS = "FETCH_SERVERS_SUCCESS";
export const FETCH_SERVER_SUCCESS = "FETCH_SERVER_SUCCESS";
export const POST_SERVER_SUCCESS = "POST_SERVER_SUCCESS";
export const PUT_SERVER_SUCCESS = "PUT_SERVER_SUCCESS";
export const DELETE_SERVER_SUCCESS = "DELETE_SERVER_SUCCESS";
